apiVersion: v1
kind: ConfigMap
metadata:
  name: sso-service-config
data:
  APP_NAME: "sso-service"
  APP_SERVICE_NAME: "sso-service"
  APP_VERSION: "latest"

  GRPC_PORT: "8080"
  GRPC_TIME: "30s"
  GRPC_TIMEOUT: "5s"
  GRPC_MAX_CONN_IDLE: "15m"
  GRPC_MAX_CONN_AGE: "30m"

  HTTP_PORT: "8081"
  HTTP_TIMEOUT: "5s"
  IDLE_TIMEOUT: "30s"
  SHUTDOWN_TIMEOUT: "30s"

  DB_USERNAME: "root"
  DB_PASSWORD: "password"
  DB_HOST: "mongodb"
  DB_PORT: "27017"
  DB_NAME: "sso"

  USER_CLIENT_HOST: "users-service.users-service.svc.cluster.local"
  USER_CLIENT_PORT: "8080"

  OTEL_IS_TLS: "false"
  OTEL_ENDPOINT: "alloy.monitoring.svc.cluster.local:4317"
  OTEL_PYROSCOPE_ENDPOINT: "http://alloy.monitoring.svc.cluster.local:4040"
  OTEL_TIMEOUT: "15s"

  VAULT_URL: "http://vault.secrets.svc.cluster.local:8200"
  VAULT_ROLE: "sso-service-role"
  VAULT_TRANSIT_NAME: "sso-service-keys"
  VAULT_SA_TOKEN_PATH: "/var/run/secrets/kubernetes.io/serviceaccount/token"
  VAULT_TRANSIT_VERSION_PATH: "/vault/secrets/key-version.txt"