apiVersion: batch/v1
kind: Job
metadata:
  name: sso-service-migrate
  annotations:
    werf.io/weight: "30"
spec:
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      imagePullSecrets:
        - name: registrysecret
      containers:
        - name: migrate
          image: sso-service-image
          command:
            - /migrations/migrate
            - -path=/migrations/schemes
            - -database=mongodb://$(DB_USER):$(DB_PASSWORD)@$(DB_HOST):$(DB_PORT)/$(DB_NAME)?sslmode=disable
            - up
          env:
            - name: DB_HOST
              value: "sso-mongodb"
            - name: DB_USER
              value: "root"
            - name: DB_PASSWORD
              value: "password"
            - name: DB_NAME
              value: "sso"
            - name: DB_PORT
              value: "27017"