apiVersion: batch/v1
kind: Job
metadata:
  name: sso-service-wait-mongodb
  annotations:
    werf.io/weight: "20"
spec:
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: waiting-mongodb
          image: busybox:1.37
          command:
            - sh
            - -c
            - |
              until nc -w 2 $(DB_HOST) $(DB_PORT); do
                echo "Waiting for mongodb...";
                sleep 2;
              done;
          env:
            - name: DB_HOST
              value: "sso-mongodb"
            - name: DB_PORT
              value: "27017"
          resources:
            requests:
              cpu: 50m
              memory: 50Mi
            limits:
              cpu: 50m
              memory: 50Mi