apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Chart.Name }}-wait-depends-rev{{ .Release.Revision }}"
  annotations:
    werf.io/weight: "10"
spec:
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: waiting-mongodb
          image: busybox
          command:
            - sh
            - -c
            - |
              until nc -w 2 $(DB_HOST) $(DB_PORT); do
                echo "Waiting for mongodb...";
                sleep 2;
              done;
          env:
            - name: DB_HOST
              value: "{{ .Release.Name }}-{{ .Values.mongodb.host }}"
            - name: DB_PORT
              value: {{ .Values.mongodb.port | quote }}
          resources:
            requests:
              cpu: 50m
              memory: 50Mi
            limits:
              cpu: 50m
              memory: 50Mi