apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sso-service

resources:
  - ../../base
  - values.yaml

helmCharts:
  - name: mongodb
    releaseName: mongodb
    namespace: sso-service
    repo: https://charts.bitnami.com/bitnami
    version: 18.6.26
    valuesFile: values.yaml