apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sso-service

resources:
  - ../../base

helmCharts:
  - name: mongodb
    releaseName: mongodb
    namespace: sso-service
    repo: https://charts.bitnami.com/bitnami
    version: 19.0.0
    valuesFile: mongo-values.yaml