apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: vault-secrets
  annotations:
    werf.io/weight: "1"
spec:
  provider: vault
  secretObjects:
    - secretName: dbpass
      type: Opaque
      data:
        - key: sso-public-key
          objectName: sso-service-rsa-key
  parameters:
    vaultAddress: {{ .Values.vault.url }}
    roleName: {{ .Values.vault.role }}
    objects: |
      - objectName: "sso-service-rsa-key"
        secretPath: "transit/keys/sso-service-rsa-key"
        secretKey: "public_key"