app:
  replicas: 3
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 1
    memory: 512Mi
  clients:
    users:
      host: "users-service.users-service.svc.cluster.local"
      port: 8080
  grpc:
    name: grpc
    port: 8080
    protocol: TCP
    time: "30s"
    timeout: "5s"
    maxIdle: "15m"
    maxAge: "30m"
  http:
    name: http
    port: 8081
    protocol: TCP
    httpTimeout: "5s"
    idleTimeout: "30s"
  shutdownTimeout: "30s"

mongodb:
  host: mongodb
  port: 27017
  auth:
    enabled: true
    rootPassword: root
    username: root
    password: password
    database: sso
  persistence:
    enabled: true
    size: 3Gi
  resources:
    requests:
      cpu: 200m
      memory: 256Mi
    limits:
      cpu: 1
      memory: 512Mi

telemetry:
  collector:
    url: "alloy.telemetry.svc.cluster.local:4317"
    timeout: "15s"
    isTls: false
  pyroscope:
    url: "http://alloy.telemetry.svc.cluster.local:4040"

privateKey:
  file: "/vault/secrets/jwt-key"

